### PR TITLE
chore: simplifies the installation procees for lega-commander

### PR DESCRIPTION
**Pull request by joshbaskaran**
Now uses `go install` instead of the bash script.

### CODE REVIEW

**Comment by kjellp** [comment]
Looks like this will require any user (uploader or downloader) to have go installed on the system. That seems to me to be a too large prerequisite to simply install a self-contained binary...

**Comment by joshbaskaran** [comment]
> Looks like this will require any user (uploader or downloader) to have go installed on the system. That seems to me to be a too large prerequisite to simply install a self-contained binary...

That's fair. We then only need to swap out some variables to it points to the correct releases in this repository.

**Comment by pavelvazquez** [comment]
Im on it on this [branch](https://github.com/ELIXIR-NO/FEGA-Norway/tree/chore/pre-deprecation-fixes) just need to find where the binaries are

**Comment by joshbaskaran** [comment]
Closing this issue as it's not needed.

**Pull request closed without merging**
